services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=iduka_mart
      - 'POSTGRES_PASSWORD=password123'
    volumes:
        - 'postgres_data:/var/lib/postgresql/data'
